[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.7

[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "pnpm run generate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm run dev"