[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.7

[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "pnpm run build"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "text/xml"
    
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[dev]
  command = "pnpm dev"
  autoLaunch = false
  targetPort = 3336
  functionsPort = 3335
  port = 3000
