// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ICarbonTime: typeof import('~icons/carbon/time')['default']
    ICarbonVideo: typeof import('~icons/carbon/video')['default']
    ICarbonVoiceActivate: typeof import('~icons/carbon/voice-activate')['default']
    README: typeof import('./components/README.md')['default']
    Testimonials: typeof import('./components/Testimonials.vue')['default']
    TopOpen: typeof import('./components/TopOpen.vue')['default']
  }
}

export { }
